# Generated by Django 3.1.2 on 2020-10-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('idcard_no', models.IntegerField()),
                ('id_type', models.CharField(choices=[('1', 'PAN'), ('2', 'Aadhar'), ('3', 'VoterID'), ('4', 'Others')], max_length=1)),
                ('address', models.TextField()),
                ('phone_no', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('meet_with', models.CharField(max_length=100)),
            ],
        ),
    ]
